version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: RenconSport
      POSTGRES_PASSWORD: RenconSport
      POSTGRES_DB: RenconSport
    ports:
      - '5432:5432'
