version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: RenconSport
      POSTGRES_PASSWORD: RenconSport
      POSTGRES_DB: RenconSport

    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  prisma-postgres-api:
    image: nodejs:alpine
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    environment:
      DB_HOSTNAME: postgres
    # command: ./wait-for.sh postgres:5432

volumes:
  postgres-data:
  pgadmin-data:
  node_modules:
